# Generated by Django 3.2.9 on 2021-11-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('date', models.DateField()),
                ('artist_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
